server:
  port: 8080

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fish?useSSL=false
    username: root
    password: yefan@813
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0               # Redis数据库索引（默认为0）
    host: localhost           # Redis服务器地址
    port: 6379                # Redis服务器连接端口
    password:                 # Redis服务器连接密码（默认为空）
    timeout: 2000
    jedis:
      pool:
        max-active: 8         # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8           # 连接池中的最大空闲连接
        max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0           # 连接池中的最小空闲连接

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.small.leaf.domain
